# Paper サーバー共通テンプレート
# overlay (lobby, survival) から参照して使用する
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
