version: "3"

services:
  vanilla:
    build: ./tools
    privileged: false
    restart: always

    ports:
      - "25565:25565"
    tty: true

    stdin_open: true

    volumes:
      - "./data:/root/data"

    environment:
      TZ: 'Asia/Tokyo'
